In [2]:
#                           Jai shree ram

In [3]:
import numpy as np 
import pandas as pd 
import re
import datetime
from urllib.parse import urlparse
import pandas as pd
import whois
import re
import tqdm
from datetime import datetime
from bs4 import BeautifulSoup
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import StandardScaler

In [4]:
df = pd.read_csv('C:\\Users\\jaite\\OneDrive\\Desktop\\FinalScripts\\2Ldataset.csv')

In [5]:
df

url        type
0               http://www.ganyuan.net/newsshow.asp?id=58  defacement
1       darkhorizons.com/news/22103/shawn-levy-attache...      benign
2                             music.yahoo.com/high-dials/      benign
3       http://www.westlondongmpresources.org.uk/index...  defacement
4                       veromi.com/Terrance-Corcoran.aspx      benign
...                                                   ...         ...
199995            http://www.salfed.com/index.php?start=7  defacement
199996                        http://triple5triple4.com/3     malware
199997  satellitetv-news.com/2010-11-nfl-regular-seaso...      benign
199998  montrealcanadiens.ca/artman/publish/article_97...      benign
199999      greatermontrealchurchofchrist.com/contact.htm      benign

[200000 rows x 2 columns]

In [6]:
df

url        type
0               http://www.ganyuan.net/newsshow.asp?id=58  defacement
1       darkhorizons.com/news/22103/shawn-levy-attache...      benign
2                             music.yahoo.com/high-dials/      benign
3       http://www.westlondongmpresources.org.uk/index...  defacement
4                       veromi.com/Terrance-Corcoran.aspx      benign
...                                                   ...         ...
199995            http://www.salfed.com/index.php?start=7  defacement
199996                        http://triple5triple4.com/3     malware
199997  satellitetv-news.com/2010-11-nfl-regular-seaso...      benign
199998  montrealcanadiens.ca/artman/publish/article_97...      benign
199999      greatermontrealchurchofchrist.com/contact.htm      benign

[200000 rows x 2 columns]

In [7]:
def url_length(url):
    return len(str(url))

df['url_length'] = df['url'].apply(lambda i: url_length(i))
df

url        type  \
0               http://www.ganyuan.net/newsshow.asp?id=58  defacement   
1       darkhorizons.com/news/22103/shawn-levy-attache...      benign   
2                             music.yahoo.com/high-dials/      benign   
3       http://www.westlondongmpresources.org.uk/index...  defacement   
4                       veromi.com/Terrance-Corcoran.aspx      benign   
...                                                   ...         ...   
199995            http://www.salfed.com/index.php?start=7  defacement   
199996                        http://triple5triple4.com/3     malware   
199997  satellitetv-news.com/2010-11-nfl-regular-seaso...      benign   
199998  montrealcanadiens.ca/artman/publish/article_97...      benign   
199999      greatermontrealchurchofchrist.com/contact.htm      benign   

        url_length  
0               41  
1               59  
2               27  
3              157  
4               33  
...            ...  
199995          39  
199996          27  
199997         120  
199998          52  
199999          45  

[200000 rows x 3 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder

lb_make = LabelEncoder()
df["class_url"] = lb_make.fit_transform(df["type"])
df["class_url"].value_counts()

class_url
0    131339
1     29765
3     28864
2     10011
4        21
Name: count, dtype: int64

In [9]:
def url_length(url):
    return len(str(url))

df['url_length'] = df['url'].apply(lambda i: url_length(i))
df

url        type  \
0               http://www.ganyuan.net/newsshow.asp?id=58  defacement   
1       darkhorizons.com/news/22103/shawn-levy-attache...      benign   
2                             music.yahoo.com/high-dials/      benign   
3       http://www.westlondongmpresources.org.uk/index...  defacement   
4                       veromi.com/Terrance-Corcoran.aspx      benign   
...                                                   ...         ...   
199995            http://www.salfed.com/index.php?start=7  defacement   
199996                        http://triple5triple4.com/3     malware   
199997  satellitetv-news.com/2010-11-nfl-regular-seaso...      benign   
199998  montrealcanadiens.ca/artman/publish/article_97...      benign   
199999      greatermontrealchurchofchrist.com/contact.htm      benign   

        url_length  class_url  
0               41          1  
1               59          0  
2               27          0  
3              157          1  
4               33          0  
...            ...        ...  
199995          39          1  
199996          27          2  
199997         120          0  
199998          52          0  
199999          45          0  

[200000 rows x 4 columns]

In [10]:
from urllib.parse import urlparse

def hostname_length(url):
    # Ensure that the URL is a string
    if isinstance(url, str):
        return len(urlparse(url).netloc)
    else:
        return 0  # or return None, depending on how you want to handle non-string inputs

# Apply the modified function
df['hostname_length'] = df['url'].apply(lambda i: hostname_length(i))
df


url        type  \
0               http://www.ganyuan.net/newsshow.asp?id=58  defacement   
1       darkhorizons.com/news/22103/shawn-levy-attache...      benign   
2                             music.yahoo.com/high-dials/      benign   
3       http://www.westlondongmpresources.org.uk/index...  defacement   
4                       veromi.com/Terrance-Corcoran.aspx      benign   
...                                                   ...         ...   
199995            http://www.salfed.com/index.php?start=7  defacement   
199996                        http://triple5triple4.com/3     malware   
199997  satellitetv-news.com/2010-11-nfl-regular-seaso...      benign   
199998  montrealcanadiens.ca/artman/publish/article_97...      benign   
199999      greatermontrealchurchofchrist.com/contact.htm      benign   

        url_length  class_url  hostname_length  
0               41          1               15  
1               59          0                0  
2               27          0                0  
3              157          1               33  
4               33          0                0  
...            ...        ...              ...  
199995          39          1               14  
199996          27          2               18  
199997         120          0                0  
199998          52          0                0  
199999          45          0                0  

[200000 rows x 5 columns]

In [11]:
def count_www(url):
    # Ensure that the URL is a string
    if isinstance(url, str):
        return url.count('www')
    else:
        return 0  # or return None, depending on how you want to handle non-string inputs

# Apply the modified function
df['count-www'] = df['url'].apply(lambda i: count_www(i))
df


url        type  \
0               http://www.ganyuan.net/newsshow.asp?id=58  defacement   
1       darkhorizons.com/news/22103/shawn-levy-attache...      benign   
2                             music.yahoo.com/high-dials/      benign   
3       http://www.westlondongmpresources.org.uk/index...  defacement   
4                       veromi.com/Terrance-Corcoran.aspx      benign   
...                                                   ...         ...   
199995            http://www.salfed.com/index.php?start=7  defacement   
199996                        http://triple5triple4.com/3     malware   
199997  satellitetv-news.com/2010-11-nfl-regular-seaso...      benign   
199998  montrealcanadiens.ca/artman/publish/article_97...      benign   
199999      greatermontrealchurchofchrist.com/contact.htm      benign   

        url_length  class_url  hostname_length  count-www  
0               41          1               15          1  
1               59          0                0          0  
2               27          0                0          0  
3              157          1               33          1  
4               33          0                0          0  
...            ...        ...              ...        ...  
199995          39          1               14          1  
199996          27          2               18          0  
199997         120          0                0          0  
199998          52          0                0          0  
199999          45          0                0          0  

[200000 rows x 6 columns]

In [12]:
def count_https(url):
    # Ensure that the URL is a string
    if isinstance(url, str):
        return url.count('https')
    else:
        return 0  # or return None, depending on how you want to handle non-string inputs

df['count-https'] = df['url'].apply(lambda i: count_https(i))

def count_http(url):
    # Ensure that the URL is a string
    if isinstance(url, str):
        return url.count('http')
    else:
        return 0  # or return None, depending on how you want to handle non-string inputs

df['count-http'] = df['url'].apply(lambda i: count_http(i))

# Display the DataFrame
df


url        type  \
0               http://www.ganyuan.net/newsshow.asp?id=58  defacement   
1       darkhorizons.com/news/22103/shawn-levy-attache...      benign   
2                             music.yahoo.com/high-dials/      benign   
3       http://www.westlondongmpresources.org.uk/index...  defacement   
4                       veromi.com/Terrance-Corcoran.aspx      benign   
...                                                   ...         ...   
199995            http://www.salfed.com/index.php?start=7  defacement   
199996                        http://triple5triple4.com/3     malware   
199997  satellitetv-news.com/2010-11-nfl-regular-seaso...      benign   
199998  montrealcanadiens.ca/artman/publish/article_97...      benign   
199999      greatermontrealchurchofchrist.com/contact.htm      benign   

        url_length  class_url  hostname_length  count-www  count-https  \
0               41          1               15          1            0   
1               59          0                0          0            0   
2               27          0                0          0            0   
3              157          1               33          1            0   
4               33          0                0          0            0   
...            ...        ...              ...        ...          ...   
199995          39          1               14          1            0   
199996          27          2               18          0            0   
199997         120          0                0          0            0   
199998          52          0                0          0            0   
199999          45          0                0          0            0   

        count-http  
0                1  
1                0  
2                0  
3                1  
4                0  
...            ...  
199995           1  
199996           1  
199997           0  
199998           0  
199999           0  

[200000 rows x 8 columns]

In [13]:
df

url        type  \
0               http://www.ganyuan.net/newsshow.asp?id=58  defacement   
1       darkhorizons.com/news/22103/shawn-levy-attache...      benign   
2                             music.yahoo.com/high-dials/      benign   
3       http://www.westlondongmpresources.org.uk/index...  defacement   
4                       veromi.com/Terrance-Corcoran.aspx      benign   
...                                                   ...         ...   
199995            http://www.salfed.com/index.php?start=7  defacement   
199996                        http://triple5triple4.com/3     malware   
199997  satellitetv-news.com/2010-11-nfl-regular-seaso...      benign   
199998  montrealcanadiens.ca/artman/publish/article_97...      benign   
199999      greatermontrealchurchofchrist.com/contact.htm      benign   

        url_length  class_url  hostname_length  count-www  count-https  \
0               41          1               15          1            0   
1               59          0                0          0            0   
2               27          0                0          0            0   
3              157          1               33          1            0   
4               33          0                0          0            0   
...            ...        ...              ...        ...          ...   
199995          39          1               14          1            0   
199996          27          2               18          0            0   
199997         120          0                0          0            0   
199998          52          0                0          0            0   
199999          45          0                0          0            0   

        count-http  
0                1  
1                0  
2                0  
3                1  
4                0  
...            ...  
199995           1  
199996           1  
199997           0  
199998           0  
199999           0  

[200000 rows x 8 columns]

In [14]:
import re

def shortening_service(url):
    # Ensure that the URL is a string
    if isinstance(url, str):
        match = re.search(
            'bit\.ly|goo\.gl|shorte\.st|go2l\.ink|x\.co|ow\.ly|t\.co|tinyurl|tr\.im|is\.gd|cli\.gs|'
            'yfrog\.com|migre\.me|ff\.im|tiny\.cc|url4\.eu|twit\.ac|su\.pr|twurl\.nl|snipurl\.com|'
            'short\.to|BudURL\.com|ping\.fm|post\.ly|Just\.as|bkite\.com|snipr\.com|fic\.kr|loopt\.us|'
            'doiop\.com|short\.ie|kl\.am|wp\.me|rubyurl\.com|om\.ly|to\.ly|bit\.do|t\.co|lnkd\.in|'
            'db\.tt|qr\.ae|adf\.ly|goo\.gl|bitly\.com|cur\.lv|tinyurl\.com|ow\.ly|bit\.ly|ity\.im|'
            'q\.gs|is\.gd|po\.st|bc\.vc|twitthis\.com|u\.to|j\.mp|buzurl\.com|cutt\.us|u\.bb|yourls\.org|'
            'x\.co|prettylinkpro\.com|scrnch\.me|filoops\.info|vzturl\.com|qr\.net|1url\.com|tweez\.me|v\.gd|'
            'tr\.im|link\.zip\.net',
            url)
        if match:
            return 1
        else:
            return 0
    else:
        return

# Apply the function to the DataFrame
df['short_url'] = df['url'].apply(lambda i: shortening_service(i))

# Display the DataFrame
df


url        type  \
0               http://www.ganyuan.net/newsshow.asp?id=58  defacement   
1       darkhorizons.com/news/22103/shawn-levy-attache...      benign   
2                             music.yahoo.com/high-dials/      benign   
3       http://www.westlondongmpresources.org.uk/index...  defacement   
4                       veromi.com/Terrance-Corcoran.aspx      benign   
...                                                   ...         ...   
199995            http://www.salfed.com/index.php?start=7  defacement   
199996                        http://triple5triple4.com/3     malware   
199997  satellitetv-news.com/2010-11-nfl-regular-seaso...      benign   
199998  montrealcanadiens.ca/artman/publish/article_97...      benign   
199999      greatermontrealchurchofchrist.com/contact.htm      benign   

        url_length  class_url  hostname_length  count-www  count-https  \
0               41          1               15          1            0   
1               59          0                0          0            0   
2               27          0                0          0            0   
3              157          1               33          1            0   
4               33          0                0          0            0   
...            ...        ...              ...        ...          ...   
199995          39          1               14          1            0   
199996          27          2               18          0            0   
199997         120          0                0          0            0   
199998          52          0                0          0            0   
199999          45          0                0          0            0   

        count-http  short_url  
0                1        0.0  
1                0        0.0  
2                0        0.0  
3                1        0.0  
4                0        0.0  
...            ...        ...  
199995           1        0.0  
199996           1        0.0  
199997           0        0.0  
199998           0        0.0  
199999           0        1.0  

[200000 rows x 9 columns]

In [15]:
df['short_url'].value_counts()

short_url
0.0    187820
1.0     12177
Name: count, dtype: int64

In [16]:
!pip install tld

In [17]:
from tld import get_tld

# Adjusting fd_length to handle non-string inputs
from urllib.parse import urlparse

def fd_length(url):
    if isinstance(url, str):  # Check if the URL is a string
        urlpath = urlparse(url).path
        try:
            return len(urlpath.split('/')[1])
        except IndexError:
            return 0
    else:
        return 0  # Handle non-string inputs


def tld_length(tld):
    if isinstance(tld, str):  # Check if the TLD is a string
        return len(tld)
    else:
        return -1  # Handle non-string inputs

from tld import get_tld

df['fd_length'] = df['url'].apply(fd_length)

# Ensure get_tld handles non-strings properly or check before applying
df['tld'] = df['url'].apply(lambda i: get_tld(i, fail_silently=True) if isinstance(i, str) else None)
df['tld_length'] = df['tld'].apply(tld_length)
df


url        type  \
0               http://www.ganyuan.net/newsshow.asp?id=58  defacement   
1       darkhorizons.com/news/22103/shawn-levy-attache...      benign   
2                             music.yahoo.com/high-dials/      benign   
3       http://www.westlondongmpresources.org.uk/index...  defacement   
4                       veromi.com/Terrance-Corcoran.aspx      benign   
...                                                   ...         ...   
199995            http://www.salfed.com/index.php?start=7  defacement   
199996                        http://triple5triple4.com/3     malware   
199997  satellitetv-news.com/2010-11-nfl-regular-seaso...      benign   
199998  montrealcanadiens.ca/artman/publish/article_97...      benign   
199999      greatermontrealchurchofchrist.com/contact.htm      benign   

        url_length  class_url  hostname_length  count-www  count-https  \
0               41          1               15          1            0   
1               59          0                0          0            0   
2               27          0                0          0            0   
3              157          1               33          1            0   
4               33          0                0          0            0   
...            ...        ...              ...        ...          ...   
199995          39          1               14          1            0   
199996          27          2               18          0            0   
199997         120          0                0          0            0   
199998          52          0                0          0            0   
199999          45          0                0          0            0   

        count-http  short_url  fd_length     tld  tld_length  
0                1        0.0         12     net           3  
1                0        0.0          4    None          -1  
2                0        0.0         10    None          -1  
3                1        0.0          9  org.uk           6  
4                0        0.0         22    None          -1  
...            ...        ...        ...     ...         ...  
199995           1        0.0          9     com           3  
199996           1        0.0          1     com           3  
199997           0        0.0         98    None          -1  
199998           0        0.0          6    None          -1  
199999           0        1.0         11    None          -1  

[200000 rows x 12 columns]

In [18]:
import re

def suspicious_words(url):
    # Ensure that the URL is a string
    if isinstance(url, str):
        match = re.search(
            'PayPal|login|signin|bank|account|update|free|lucky|service|bonus|'
            'ebayisapi|webscr',
            url)
        if match:
            return 1
        else:
            return 0
    else:
        return 0  # Return 0 for non-string inputs

# Apply the function to the DataFrame
df['sus_url'] = df['url'].apply(lambda i: suspicious_words(i))



df

url        type  \
0               http://www.ganyuan.net/newsshow.asp?id=58  defacement   
1       darkhorizons.com/news/22103/shawn-levy-attache...      benign   
2                             music.yahoo.com/high-dials/      benign   
3       http://www.westlondongmpresources.org.uk/index...  defacement   
4                       veromi.com/Terrance-Corcoran.aspx      benign   
...                                                   ...         ...   
199995            http://www.salfed.com/index.php?start=7  defacement   
199996                        http://triple5triple4.com/3     malware   
199997  satellitetv-news.com/2010-11-nfl-regular-seaso...      benign   
199998  montrealcanadiens.ca/artman/publish/article_97...      benign   
199999      greatermontrealchurchofchrist.com/contact.htm      benign   

        url_length  class_url  hostname_length  count-www  count-https  \
0               41          1               15          1            0   
1               59          0                0          0            0   
2               27          0                0          0            0   
3              157          1               33          1            0   
4               33          0                0          0            0   
...            ...        ...              ...        ...          ...   
199995          39          1               14          1            0   
199996          27          2               18          0            0   
199997         120          0                0          0            0   
199998          52          0                0          0            0   
199999          45          0                0          0            0   

        count-http  short_url  fd_length     tld  tld_length  sus_url  
0                1        0.0         12     net           3        0  
1                0        0.0          4    None          -1        0  
2                0        0.0         10    None          -1        0  
3                1        0.0          9  org.uk           6        0  
4                0        0.0         22    None          -1        0  
...            ...        ...        ...     ...         ...      ...  
199995           1        0.0          9     com           3        0  
199996           1        0.0          1     com           3        0  
199997           0        0.0         98    None          -1        0  
199998           0        0.0          6    None          -1        0  
199999           0        1.0         11    None          -1        0  

[200000 rows x 13 columns]

In [19]:
df['sus_url'].value_counts()

sus_url
0    186417
1     13583
Name: count, dtype: int64

In [20]:
from urllib.parse import urlparse
import re

def abnormal_url(url):
    # Ensure that the URL is a string
    if isinstance(url, str):
        hostname = urlparse(url).hostname
        hostname = str(hostname)  # Convert hostname to string to ensure it's not None
        match = re.search(hostname, url)
        if match:
            return 1
        else:
            return 0
    else:
        return 0  # Return 0 for non-string inputs

# Apply the function to the DataFrame
df['abnormal_url'] = df['url'].apply(lambda i: abnormal_url(i))
df


url        type  \
0               http://www.ganyuan.net/newsshow.asp?id=58  defacement   
1       darkhorizons.com/news/22103/shawn-levy-attache...      benign   
2                             music.yahoo.com/high-dials/      benign   
3       http://www.westlondongmpresources.org.uk/index...  defacement   
4                       veromi.com/Terrance-Corcoran.aspx      benign   
...                                                   ...         ...   
199995            http://www.salfed.com/index.php?start=7  defacement   
199996                        http://triple5triple4.com/3     malware   
199997  satellitetv-news.com/2010-11-nfl-regular-seaso...      benign   
199998  montrealcanadiens.ca/artman/publish/article_97...      benign   
199999      greatermontrealchurchofchrist.com/contact.htm      benign   

        url_length  class_url  hostname_length  count-www  count-https  \
0               41          1               15          1            0   
1               59          0                0          0            0   
2               27          0                0          0            0   
3              157          1               33          1            0   
4               33          0                0          0            0   
...            ...        ...              ...        ...          ...   
199995          39          1               14          1            0   
199996          27          2               18          0            0   
199997         120          0                0          0            0   
199998          52          0                0          0            0   
199999          45          0                0          0            0   

        count-http  short_url  fd_length     tld  tld_length  sus_url  \
0                1        0.0         12     net           3        0   
1                0        0.0          4    None          -1        0   
2                0        0.0         10    None          -1        0   
3                1        0.0          9  org.uk           6        0   
4                0        0.0         22    None          -1        0   
...            ...        ...        ...     ...         ...      ...   
199995           1        0.0          9     com           3        0   
199996           1        0.0          1     com           3        0   
199997           0        0.0         98    None          -1        0   
199998           0        0.0          6    None          -1        0   
199999           0        1.0         11    None          -1        0   

        abnormal_url  
0                  1  
1                  0  
2                  0  
3                  1  
4                  0  
...              ...  
199995             1  
199996             1  
199997             0  
199998             0  
199999             0  

[200000 rows x 14 columns]

In [21]:
df['abnormal_url'].value_counts()

abnormal_url
0    142114
1     57886
Name: count, dtype: int64

In [22]:
import re

def having_ip_address(url):
    # Ensure that the URL is a string
    if isinstance(url, str):
        match = re.search(
            '(([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.'
            '([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\/)|'  # IPv4
            '((0x[0-9a-fA-F]{1,2})\\.(0x[0-9a-fA-F]{1,2})\\.'
            '(0x[0-9a-fA-F]{1,2})\\.(0x[0-9a-fA-F]{1,2})\\/)'  # IPv4 in hexadecimal
            '(?:[a-fA-F0-9]{1,4}:){7}[a-fA-F0-9]{1,4}',  # Ipv6
            url)
        if match:
            return 1
        else:
            return 0
    else:
        return 0  # Return 0 for non-string inputs

# Apply the function to the DataFrame
df['use_of_ip_address'] = df['url'].apply(lambda i: having_ip_address(i))
df


url        type  \
0               http://www.ganyuan.net/newsshow.asp?id=58  defacement   
1       darkhorizons.com/news/22103/shawn-levy-attache...      benign   
2                             music.yahoo.com/high-dials/      benign   
3       http://www.westlondongmpresources.org.uk/index...  defacement   
4                       veromi.com/Terrance-Corcoran.aspx      benign   
...                                                   ...         ...   
199995            http://www.salfed.com/index.php?start=7  defacement   
199996                        http://triple5triple4.com/3     malware   
199997  satellitetv-news.com/2010-11-nfl-regular-seaso...      benign   
199998  montrealcanadiens.ca/artman/publish/article_97...      benign   
199999      greatermontrealchurchofchrist.com/contact.htm      benign   

        url_length  class_url  hostname_length  count-www  count-https  \
0               41          1               15          1            0   
1               59          0                0          0            0   
2               27          0                0          0            0   
3              157          1               33          1            0   
4               33          0                0          0            0   
...            ...        ...              ...        ...          ...   
199995          39          1               14          1            0   
199996          27          2               18          0            0   
199997         120          0                0          0            0   
199998          52          0                0          0            0   
199999          45          0                0          0            0   

        count-http  short_url  fd_length     tld  tld_length  sus_url  \
0                1        0.0         12     net           3        0   
1                0        0.0          4    None          -1        0   
2                0        0.0         10    None          -1        0   
3                1        0.0          9  org.uk           6        0   
4                0        0.0         22    None          -1        0   
...            ...        ...        ...     ...         ...      ...   
199995           1        0.0          9     com           3        0   
199996           1        0.0          1     com           3        0   
199997           0        0.0         98    None          -1        0   
199998           0        0.0          6    None          -1        0   
199999           0        1.0         11    None          -1        0   

        abnormal_url  use_of_ip_address  
0                  1                  0  
1                  0                  0  
2                  0                  0  
3                  1                  0  
4                  0                  0  
...              ...                ...  
199995             1                  0  
199996             1                  0  
199997             0                  0  
199998             0                  0  
199999             0                  0  

[200000 rows x 15 columns]

In [23]:
df['use_of_ip_address'].value_counts()

use_of_ip_address
0    197689
1      2311
Name: count, dtype: int64

In [24]:
!pip install googlesearch-python

In [25]:
from googlesearch import search
def google_index(url):
    site = search(url, 5)
    return 1 if site else 0
df['google_index'] = df['url'].apply(lambda i: google_index(i))
df

url        type  \
0               http://www.ganyuan.net/newsshow.asp?id=58  defacement   
1       darkhorizons.com/news/22103/shawn-levy-attache...      benign   
2                             music.yahoo.com/high-dials/      benign   
3       http://www.westlondongmpresources.org.uk/index...  defacement   
4                       veromi.com/Terrance-Corcoran.aspx      benign   
...                                                   ...         ...   
199995            http://www.salfed.com/index.php?start=7  defacement   
199996                        http://triple5triple4.com/3     malware   
199997  satellitetv-news.com/2010-11-nfl-regular-seaso...      benign   
199998  montrealcanadiens.ca/artman/publish/article_97...      benign   
199999      greatermontrealchurchofchrist.com/contact.htm      benign   

        url_length  class_url  hostname_length  count-www  count-https  \
0               41          1               15          1            0   
1               59          0                0          0            0   
2               27          0                0          0            0   
3              157          1               33          1            0   
4               33          0                0          0            0   
...            ...        ...              ...        ...          ...   
199995          39          1               14          1            0   
199996          27          2               18          0            0   
199997         120          0                0          0            0   
199998          52          0                0          0            0   
199999          45          0                0          0            0   

        count-http  short_url  fd_length     tld  tld_length  sus_url  \
0                1        0.0         12     net           3        0   
1                0        0.0          4    None          -1        0   
2                0        0.0         10    None          -1        0   
3                1        0.0          9  org.uk           6        0   
4                0        0.0         22    None          -1        0   
...            ...        ...        ...     ...         ...      ...   
199995           1        0.0          9     com           3        0   
199996           1        0.0          1     com           3        0   
199997           0        0.0         98    None          -1        0   
199998           0        0.0          6    None          -1        0   
199999           0        1.0         11    None          -1        0   

        abnormal_url  use_of_ip_address  google_index  
0                  1                  0             1  
1                  0                  0             1  
2                  0                  0             1  
3                  1                  0             1  
4                  0                  0             1  
...              ...                ...           ...  
199995             1                  0             1  
199996             1                  0             1  
199997             0                  0             1  
199998             0                  0             1  
199999             0                  0             1  

[200000 rows x 16 columns]

In [26]:
df.isnull().sum()

url                       3
type                     21
url_length                0
class_url                 0
hostname_length           0
count-www                 0
count-https               0
count-http                0
short_url                 3
fd_length                 0
tld                  145878
tld_length                0
sus_url                   0
abnormal_url              0
use_of_ip_address         0
google_index              0
dtype: int64

In [27]:
df

url        type  \
0               http://www.ganyuan.net/newsshow.asp?id=58  defacement   
1       darkhorizons.com/news/22103/shawn-levy-attache...      benign   
2                             music.yahoo.com/high-dials/      benign   
3       http://www.westlondongmpresources.org.uk/index...  defacement   
4                       veromi.com/Terrance-Corcoran.aspx      benign   
...                                                   ...         ...   
199995            http://www.salfed.com/index.php?start=7  defacement   
199996                        http://triple5triple4.com/3     malware   
199997  satellitetv-news.com/2010-11-nfl-regular-seaso...      benign   
199998  montrealcanadiens.ca/artman/publish/article_97...      benign   
199999      greatermontrealchurchofchrist.com/contact.htm      benign   

        url_length  class_url  hostname_length  count-www  count-https  \
0               41          1               15          1            0   
1               59          0                0          0            0   
2               27          0                0          0            0   
3              157          1               33          1            0   
4               33          0                0          0            0   
...            ...        ...              ...        ...          ...   
199995          39          1               14          1            0   
199996          27          2               18          0            0   
199997         120          0                0          0            0   
199998          52          0                0          0            0   
199999          45          0                0          0            0   

        count-http  short_url  fd_length     tld  tld_length  sus_url  \
0                1        0.0         12     net           3        0   
1                0        0.0          4    None          -1        0   
2                0        0.0         10    None          -1        0   
3                1        0.0          9  org.uk           6        0   
4                0        0.0         22    None          -1        0   
...            ...        ...        ...     ...         ...      ...   
199995           1        0.0          9     com           3        0   
199996           1        0.0          1     com           3        0   
199997           0        0.0         98    None          -1        0   
199998           0        0.0          6    None          -1        0   
199999           0        1.0         11    None          -1        0   

        abnormal_url  use_of_ip_address  google_index  
0                  1                  0             1  
1                  0                  0             1  
2                  0                  0             1  
3                  1                  0             1  
4                  0                  0             1  
...              ...                ...           ...  
199995             1                  0             1  
199996             1                  0             1  
199997             0                  0             1  
199998             0                  0             1  
199999             0                  0             1  

[200000 rows x 16 columns]

In [28]:
X = df[['use_of_ip_address','abnormal_url', 'google_index', 'count-www',
        'short_url', 'count-https','count-http', 'url_length','hostname_length', 'sus_url', 'fd_length', 'tld_length']]

y = df['class_url']

In [29]:
X

use_of_ip_address  abnormal_url  google_index  count-www  short_url  \
0                       0             1             1          1        0.0   
1                       0             0             1          0        0.0   
2                       0             0             1          0        0.0   
3                       0             1             1          1        0.0   
4                       0             0             1          0        0.0   
...                   ...           ...           ...        ...        ...   
199995                  0             1             1          1        0.0   
199996                  0             1             1          0        0.0   
199997                  0             0             1          0        0.0   
199998                  0             0             1          0        0.0   
199999                  0             0             1          0        1.0   

        count-https  count-http  url_length  hostname_length  sus_url  \
0                 0           1          41               15        0   
1                 0           0          59                0        0   
2                 0           0          27                0        0   
3                 0           1         157               33        0   
4                 0           0          33                0        0   
...             ...         ...         ...              ...      ...   
199995            0           1          39               14        0   
199996            0           1          27               18        0   
199997            0           0         120                0        0   
199998            0           0          52                0        0   
199999            0           0          45                0        0   

        fd_length  tld_length  
0              12           3  
1               4          -1  
2              10          -1  
3               9           6  
4              22          -1  
...           ...         ...  
199995          9           3  
199996          1           3  
199997         98          -1  
199998          6          -1  
199999         11          -1  

[200000 rows x 12 columns]

In [30]:

X_train, X_test, y_train, y_test = train_test_split(X, y,stratify=y, test_size=0.2, shuffle=True, random_state=5)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [31]:
print(f"X_train Shape : {X_train.shape}")
print(f"Y_train Shape : {y_train.shape}")
print(f"X_test  Shape : {X_test.shape}")
print(f"Y_test  Shape : {y_test.shape}")

X_train Shape : (160000, 12)
Y_train Shape : (160000,)
X_test  Shape : (40000, 12)
Y_test  Shape : (40000,)


In [32]:
from sklearn.linear_model import LogisticRegression

classifier1 = LogisticRegression(max_iter=1000, random_state=0)


In [33]:
df.isnull().sum()

url                       3
type                     21
url_length                0
class_url                 0
hostname_length           0
count-www                 0
count-https               0
count-http                0
short_url                 3
fd_length                 0
tld                  145878
tld_length                0
sus_url                   0
abnormal_url              0
use_of_ip_address         0
google_index              0
dtype: int64

In [34]:
from sklearn.impute import SimpleImputer
import numpy

imputer = SimpleImputer(strategy='mean')  # or 'median', 'most_frequent', etc.
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)  # Use the same imputer as used for the training set


In [35]:
df.fillna(0, inplace=True)


In [36]:
df.isnull().sum()

url                  0
type                 0
url_length           0
class_url            0
hostname_length      0
count-www            0
count-https          0
count-http           0
short_url            0
fd_length            0
tld                  0
tld_length           0
sus_url              0
abnormal_url         0
use_of_ip_address    0
google_index         0
dtype: int64

In [37]:
# classifier1.fit(X_train.values, y_train.values)
# y_pred1 = classifier1.predict(X_test.values)
classifier1.fit(X_train, y_train)
y_pred1 = classifier1.predict(X_test)


c:\Users\jaite\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [38]:
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(y_test, y_pred1)
print(cm1)

[[25152   471   170   475     0]
 [  454  5320   106    73     0]
 [  358   430  1143    71     0]
 [ 2605   656   188  2324     0]
 [    4     0     0     0     0]]


In [39]:
from sklearn.metrics import accuracy_score

accuracy1 = accuracy_score(y_test, y_pred1)
print("Accuracy1:", accuracy1)

Accuracy1: 0.848475


In [40]:
X

use_of_ip_address  abnormal_url  google_index  count-www  short_url  \
0                       0             1             1          1        0.0   
1                       0             0             1          0        0.0   
2                       0             0             1          0        0.0   
3                       0             1             1          1        0.0   
4                       0             0             1          0        0.0   
...                   ...           ...           ...        ...        ...   
199995                  0             1             1          1        0.0   
199996                  0             1             1          0        0.0   
199997                  0             0             1          0        0.0   
199998                  0             0             1          0        0.0   
199999                  0             0             1          0        1.0   

        count-https  count-http  url_length  hostname_length  sus_url  \
0                 0           1          41               15        0   
1                 0           0          59                0        0   
2                 0           0          27                0        0   
3                 0           1         157               33        0   
4                 0           0          33                0        0   
...             ...         ...         ...              ...      ...   
199995            0           1          39               14        0   
199996            0           1          27               18        0   
199997            0           0         120                0        0   
199998            0           0          52                0        0   
199999            0           0          45                0        0   

        fd_length  tld_length  
0              12           3  
1               4          -1  
2              10          -1  
3               9           6  
4              22          -1  
...           ...         ...  
199995          9           3  
199996          1           3  
199997         98          -1  
199998          6          -1  
199999         11          -1  

[200000 rows x 12 columns]

In [41]:
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier

classifier5 = RandomForestClassifier(n_estimators=100, max_features='sqrt')
classifier5.fit(X_train, y_train)  # Removed .values
y_pred5 = classifier5.predict(X_test)  # Removed .values


In [42]:
cm5 = confusion_matrix(y_test, y_pred5)
print(cm5)

[[25718    57    13   480     0]
 [   73  5733    22   124     1]
 [   82    64  1801    55     0]
 [ 2158   262    33  3320     0]
 [    2     2     0     0     0]]


In [43]:
accuracy5 = metrics.accuracy_score(y_test, y_pred5)
print("Accuracy5:", accuracy5)

Accuracy5: 0.9143


In [44]:
data = {
    'Model': ['LogisticRegression', 'RandomForestClassifier'],
    'Accuracy': [accuracy1, accuracy5]
}

accuracy_table = pd.DataFrame(data)
print(accuracy_table)

                    Model  Accuracy
0      LogisticRegression  0.848475
1  RandomForestClassifier  0.914300


In [45]:
def get_url(url):
    
    status = []
    
    status.append(having_ip_address(url))
    status.append(abnormal_url(url))
    status.append(count_www(url))

    status.append(shortening_service(url))
    status.append(count_https(url))
    status.append(count_http(url))
    
    status.append(url_length(url))
    status.append(hostname_length(url))
    status.append(suspicious_words(url))
    status.append(google_index(url))
    status.append(fd_length(url))
    tld = get_tld(url,fail_silently=True)
      
    status.append(tld_length(tld))

    return status

In [46]:
def model_predict5(test_url):
    features_test = get_url(test_url)
    features_test = np.array(features_test).reshape((1, -1))

    pred = classifier5.predict(features_test)
    if int(pred[0]) == 0:
        res="Bening"
        return res
    
    elif int(pred[0]) == 1:
        res="Defacement"
        return res
    
    elif int(pred[0]) == 2:
        res="Phising"
        return res
        
    elif int(pred[0]) == 3:
        res="Malware"
        return res

In [59]:
urls = ['https://www.bitrocket.club']
print("----------------------------------------------")
print("RandomForest")
for url in urls:
     print(model_predict5(url))

----------------------------------------------
RandomForest
Malware


In [51]:
import pickle
with open('fake_copied.pkl', 'wb') as file:
    pickle.dump(classifier5,file)

In [49]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pickle

# Convert all entries in the 'url' column to strings
corpus = df['url'].astype(str).tolist()

# Create TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the text data
X = tfidf_vectorizer.fit_transform(corpus)

# Save the vectorizer to a file using pickle
with open('tfidf_vectorizer.pkl', 'wb') as file:
    pickle.dump(tfidf_vectorizer, file)
